// angular/gianluigitrontini.github.io/src/app/components/shared/header/header.component.ts
import { Component, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss'
})
export class HeaderComponent {
  isHamburgerOpen = false;

  navigation = [
    {
      name: "About",
    },
    {
      name: "Projects",
    },
    {
      name: "Contact",
    },
  ];

  size: { height: number; width: number; } = { width: 1024, height: 0 };

  @HostListener("window:resize")
  onResize() {
    this.size = {
      ...this.size,
      width: window.innerWidth
    }
  }

  setIsHamburgerOpen(value: boolean): void {
    console.log('hamburger TODO')
  }
}

<header>
    <div class="container">
        <div class="flex items-center justify-between w-full">
            <div class="logo-box">
                <img class="logo" src="assets/animated-logo.gif" alt="" />
            </div>

            @if (size.width >= 1024) {
            <nav>
                <ul class="flex items-center gap-8">
                    @for (nav of navigation; track nav.name) {
                    <li>
                        <a [href]="'#' + nav.name.toLowerCase()">
                            <button (click)="setIsHamburgerOpen(false)">
                                {{nav.name}}
                            </button>
                        </a>
                    </li>
                    }
                </ul>
            </nav>
            } @else {
            <svg class="w-8 h-8" (click)="setIsHamburgerOpen(!isHamburgerOpen)" xmlns="http://www.w3.org/2000/svg"
                class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
            </svg>

            <div [ngClass]="{
                    'fixed top-0 left-0 right-0 bottom-0 flex-col items-center justify-center bg-white z-10': true,
                    'flex': isHamburgerOpen, 
                    'hidden': !isHamburgerOpen 
                    }">
                <nav>
                    <ul class="flex flex-col gap-8 text-center text-4xl">
                        @for (nav of navigation; track nav.name) {
                        <li>
                            <a [href]="'#' + nav.name.toLowerCase()">
                                <button (click)="setIsHamburgerOpen(false)">
                                    {{nav.name}}
                                </button>
                            </a>
                        </li>
                        }
                        <li class="border-t-2 border-gray-500">
                            <button class="btn btn-outline text-2xl mt-8" (click)="setIsHamburgerOpen(false)">
                                Close
                            </button>
                        </li>
                    </ul>
                </nav>
            </div>
            }
        </div>
    </div>
</header>

// src/components/global/Header/Header.tsx
import { useEffect, useState } from "react";
import useWindowSize from "../../../hooks/useWindowSize";
import { HamburgerIcon } from "../../utils/Icon";

import { Link } from "react-scroll";

function Header() {
  const size = useWindowSize();
  const [isHamburgerOpen, setIsHamburgerOpen] = useState(false);

  useEffect(() => {
    const body = document.querySelector("body");

    isHamburgerOpen
      ? body?.classList.add("overflow-y-hidden")
      : body?.classList.remove("overflow-y-hidden");
  }, [isHamburgerOpen]);

  const navigation = [
    {
      name: "About",
    },
    {
      name: "Projects",
    },
    {
      name: "Contact",
    },
  ];

  const MobileNav = () => {
    return (
      <>
        <HamburgerIcon
          onClick={() => setIsHamburgerOpen(!isHamburgerOpen)}
          className="w-8 h-8"
        />

        <div
          className={`fixed top-0 left-0 right-0 bottom-0 flex-col items-center justify-center bg-white z-10 ${
            isHamburgerOpen ? "flex" : "hidden"
          }`}
        >
          <nav>
            <ul className="flex flex-col gap-8 text-center text-4xl">
              {navigation.map((nav, i) => (
                <li key={i}>
                  <Link
                    to={nav.name.toLowerCase()}
                    spy={true}
                    smooth={true}
                    offset={-70}
                    duration={500}
                  >
                    <button onClick={() => setIsHamburgerOpen(false)}>
                      {nav.name}
                    </button>
                  </Link>
                </li>
              ))}
              <li className="border-t-2 border-gray-500">
                <button
                  className="btn btn-outline text-2xl mt-8"
                  onClick={() => setIsHamburgerOpen(false)}
                >
                  Close
                </button>
              </li>
            </ul>
          </nav>
        </div>
      </>
    );
  };

  const DesktopNav = () => {
    return (
      <nav>
        <ul className="flex items-center gap-8">
          {navigation.map((nav, i) => (
            <li key={i}>
              <Link
                to={nav.name.toLowerCase()}
                spy={true}
                smooth={true}
                offset={-70}
                duration={500}
              >
                <button onClick={() => setIsHamburgerOpen(false)}>
                  {nav.name}
                </button>
              </Link>
            </li>
          ))}
        </ul>
      </nav>
    );
  };

  return (
    <header>
      <div className="container">
        <div className="flex items-center justify-between w-full">
          <div className="logo-box">
            <img className="logo" src="images/animated-logo.gif" alt="" />
          </div>

          {size && size.width! >= 1024 ? <DesktopNav /> : <MobileNav />}
        </div>
      </div>
    </header>
  );
}

export default Header;
