// astro/src/react-website/components/Homepage/Projects/Projects.tsx
import React from "react";
import Section from "../../global/Section";

import { Link } from "react-router-dom";

import { projects } from "../../../data";
import Project from "./Project";

export interface ProjectInterface {
  name: string;
  slug: string;
  repoName: string;
  description: string;
  image: any;
  logo?: any;
  status: string;
  linkToProject: string;
  hasCoverImage: boolean;
  hidden: boolean;
}

const Projects = () => {
  return (
    <Section id="projects" title="Projects">
      <div className="projects--wrapper">
        {projects.map(
          (prj, i) =>
            !prj.hidden && (
              <Link key={i} to={`projects/${prj.slug}`}>
                <Project project={prj} />
              </Link>
            )
        )}
      </div>
    </Section>
  );
};

export default Projects;

// angular/gianluigitrontini.github.io/src/app/components/homepage/projects/projects.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { ProjectService } from '../../../services/project/project.service';
import { ProjectComponent } from './project/project.component';

export interface ProjectInterface {
  name: string;
  slug: string;
  repoName: string;
  description: string;
  image: any;
  logo?: any;
  status: string;
  linkToProject: string;
  hasCoverImage: boolean;
  hidden: boolean;
}

@Component({
  selector: 'app-projects',
  standalone: true,
  imports: [CommonModule, ProjectComponent],
  templateUrl: './projects.component.html',
  styleUrl: './projects.component.scss'
})
export class ProjectsComponent {
  projects: ProjectInterface[] = [];

  constructor(private projectService: ProjectService) { }

  ngOnInit() {
    this.fetchProjects();
  }

  private fetchProjects() {
    this.projectService.fetchProjects$().subscribe((progetti: any) => {
      console.log(progetti)
      this.projects = progetti;
    })
  }
}

<section id="projects" class="flex flex-col container">
    <h2 class="title text-left">
        Progetti
    </h2>

    <div class="projects--wrapper">
        @for (project of projects; track project.slug) {
        @if (project.hidden === false) {
        <a [href]="'projects/' + project.slug">
            <app-project [project]="project" />
        </a>
        }
        }
    </div>
</section>
