// src/components/Homepage/Projects/Project.tsx
import React from "react";
import { ProjectInterface } from "./Projects";
import Status from "./Status";

function Project({ project }: { project: ProjectInterface }) {
  return (
    <div className="projects--item">
      <Status status={project.status} />
      {!project.hasCoverImage && (
        <h3 className="absolute top-[50%] left-[50%] text-center transform translate-y-[-50%] translate-x-[-50%] text-3xl text-black opacity-30 font-bold tracking-wider">
          {project.name}
        </h3>
      )}
      <img src={project.image && project.image} alt={project.name} />
      <button className="projects--info-overlay">
        <h3 className="project--title font-bold">{project.name}</h3>
        <p className="project--description">{project.description}</p>
      </button>
    </div>
  );
}

export default Project;

// angular/gianluigitrontini.github.io/src/app/components/homepage/projects/project/project.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { ProjectInterface } from '../projects.component';

@Component({
  selector: 'app-project',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './project.component.html',
  styleUrl: './project.component.scss'
})
export class ProjectComponent {
  @Input() project!: ProjectInterface;

}

<div class="projects--item">
    <div class="flex items-center absolute z-50 top-2 right-2 text-white uppercase text-sm">
        <span [ngClass]="{'rounded-full inline-block w-2 h-2 shadow-lg mr-2': true,
              'bg-green-400': project.status === 'Active',
              'bg-yellow-400': project.status === 'In Progress',
              'bg-blue-400': project.status === 'Demo',
               'bg-red-400': project.status === 'Offline'
               }"></span>
        {{project.status}}
    </div>

    @if (!project.hasCoverImage) {
    <h3 class=" absolute top-[50%] left-[50%] text-center transform translate-y-[-50%] translate-x-[-50%] text-3xl
            text-black opacity-30 font-bold tracking-wider">
        {{project.name}}
    </h3>
    }

    <img [src]="project.image" [alt]="project.name" />

    <button class="projects--info-overlay">
        <h3 class="project--title font-bold">{{project.name}}</h3>
        <p class="project--description">{{project.description}}</p>
    </button>
</div>
